<?php

namespace AppBundle\Repository\module;

/**
 * ExpenseModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
