<?php

namespace AppBundle\Repository\module;

/**
 * ExpenseProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseProposalRepository extends \Doctrine\ORM\EntityRepository
{
}
