<?php

namespace AppBundle\Repository\Module;

/**
 * KittyModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KittyModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
