<?php

namespace AppBundle\Repository\Module;

/**
 * KittyParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KittyParticipationRepository extends \Doctrine\ORM\EntityRepository
{
}
