<?php

namespace AppBundle\Repository\module;

use Doctrine\ORM\EntityRepository;

/**
 * PollProposalElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollProposalElementRepository extends EntityRepository
{
}
