<?php

namespace AppBundle\Repository\Module;

use Doctrine\ORM\EntityRepository;

/**
 * PollProposalResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollProposalResponseRepository extends EntityRepository
{
}
