<?php

namespace AppBundle\Repository\module;

use Doctrine\ORM\EntityRepository;

/**
 * PollProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollProposalRepository extends EntityRepository
{
}
