<?php

namespace AppBundle\Repository\module;

/**
 * PollModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
