<?php

namespace AppBundle\Repository\Module;

use Doctrine\ORM\EntityRepository;

/**
 * PollProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollProposalRepository extends EntityRepository
{
    public function findOrderedByEventToken($eventToken)
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT m, -m.orderIndex AS HIDDEN inversedOrderIndex FROM ".Module::class." m WHERE m.event = 
                          (SELECT e FROM ".Event::class." e WHERE e.token = :eventToken)
                          ORDER BY inversedOrderIndex DESC"
        );
        $query->execute(array(
            'eventToken' => $eventToken
        ));
        return $query->getResult();
    }
}
