<?php

namespace AppBundle\Repository\module;

/**
 * ProposalElementResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposalElementResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
