<?php

namespace AppBundle\Repository\module;

/**
 * ProposalElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposalElementRepository extends \Doctrine\ORM\EntityRepository
{
}
