<?php

namespace ATUserBundle\Repository;

use ATUserBundle\Entity\Contact;
use ATUserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findUserContacts(User $user, $search = null, $nbResult = 10, $pageIdx = 1, $sort = array())
    {
        $query = $this->createQueryBuilder('c');
        $query->addSelect('CASE WHEN linked.pseudo IS NULL OR linked.pseudo = \'\' THEN linked.username ELSE linked.pseudo END AS HIDDEN displayableName');
        $query->where($query->expr()->andX(
            $query->expr()->eq("c.owner", ":user"),
            $query->expr()->eq("c.status", $query->expr()->literal(Contact::STATUS_VALID))
        ));
        $query->setParameter('user', $user);
        $query->leftJoin('c.linked', 'linked');
        if (!(empty($search))) {
            $search = "%" . trim($search) . "%";
            $query
                ->andWhere(
                    $query->expr()->orX(
                        $query->expr()->like("linked.pseudo", ':search'),
                        $query->expr()->like("linked.username", ':search')
                    )
                )
                ->setParameter('search', $search);
        }

        if (is_array($sort)) {
            foreach ($sort as $key => $value) {
                if($key == 'name'){
                    $query->addOrderBy('displayableName', $value);
                }else if (property_exists(User::class, $key)) {

                }
            }
        }

        if ($nbResult > 0) {
            $query
                ->setFirstResult(($pageIdx - 1) * $nbResult)
                ->setMaxResults($nbResult);
        }
        return $query->getQuery()->getResult();
    }

    public
    function countUserContacts(User $user, $search = null)
    {
        $query = $this->createQueryBuilder("c");
        $query->select('count(c.id)');

        $query->where($query->expr()->andX(
            $query->expr()->eq("c.owner", ":user"),
            $query->expr()->eq("c.status", $query->expr()->literal(Contact::STATUS_VALID))
        ));
        $query->setParameter('user', $user);
        $query->leftJoin('c.linked', 'linked');
        if (!(empty($search))) {
            $search = "%" . trim($search) . "%";
            $query
                ->andWhere(
                    $query->expr()->orX(
                        $query->expr()->like("linked.pseudo", ':search'),
                        $query->expr()->like("linked.username", ':search')
                    )
                )
                ->setParameter('search', $search);
        }
        return $query->getQuery()->getResult(Query::HYDRATE_SINGLE_SCALAR);
    }
}
