<?php

namespace ATUserBundle\Repository;

/**
 * UserAboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAboutRepository extends \Doctrine\ORM\EntityRepository
{
}
