<?php

namespace AppBundle\Repository;

/**
 * EventInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventInvitationRepository extends \Doctrine\ORM\EntityRepository
{
}
