<?php

namespace AppBundle\Repository;

/**
 * ModuleInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleInvitationRepository extends \Doctrine\ORM\EntityRepository
{
}
