<?php

namespace AppBundle\Repository;

/**
 * PaymentModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
