imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@ATUserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    avatar_directory: '%kernel.root_dir%/../web/uploads/user/avatar'
    event_picture_directory: '%kernel.root_dir%/../web/uploads/events/pictures'
    pollproposalelement_picture_directory: '%kernel.root_dir%/../web/uploads/events/pollmodule/pollproposalelement/pictures'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        locale: "%locale%"
        base_template: "base.html.twig"
        google_analytics_ua: "%universal_analytics%"
        google_client_id: "%oauth.google.id%"
        google_maps_api_id: "%maps_api.google.id%"
        facebook_client_id: "%oauth.facebook.id%"
        display_beta: "%is_beta%"
        form_client_validation: true
    form_themes:
        - 'Form/app_forms_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles: [ 'AppBundle', 'ATUserBundle','FOSCommentBundle' ]

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        types:
            enum_appuser_status: AppBundle\Utils\enum\AppUserStatus
            enum_contactinfo_type: AppBundle\Utils\enum\ContactInfoType
            enum_contact_status: AppBundle\Utils\enum\ContactStatus
            enum_eventinvitation_answer: AppBundle\Utils\enum\EventInvitationAnswer
            enum_eventinvitation_status: AppBundle\Utils\enum\EventInvitationStatus
            enum_event_status: AppBundle\Utils\enum\EventStatus
            enum_expenseelement_type: AppBundle\Utils\enum\ExpenseElementType
            enum_payment_feeapplication: AppBundle\Utils\enum\FeeApplication
            enum_gender: AppBundle\Utils\enum\Gender
            enum_legal_status: AppBundle\Utils\enum\LegalStatus
            enum_marital_status: AppBundle\Utils\enum\MaritalStatus
            enum_moduleinvitation_status: AppBundle\Utils\enum\ModuleInvitationStatus
            enum_module_status: AppBundle\Utils\enum\ModuleStatus
            enum_pollproposal_elementtype: AppBundle\Utils\enum\PollElementType
            enum_pollproposal_response: AppBundle\Utils\enum\PollProposalResponse
            enum_pollmodule_votingtype: AppBundle\Utils\enum\PollModuleVotingType
            enum_pollmodule_type: AppBundle\Utils\enum\PollModuleType
            enum_transaction_status: AppBundle\Utils\enum\TransactionStatus
            enum_payment_transactiontrigger: AppBundle\Utils\enum\TransactionTrigger
            enum_dayofweek: AppBundle\Utils\enum\DayOfWeek
        connections:
            default:
                driver:   pdo_mysql
                server_version: 5.5
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
#    spool:
#        type:                 file
#        path:                 '%kernel.cache_dir%/swiftmailer/spool'

# FOS_User
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ATUserBundle\Entity\AccountUser
    use_flash_notifications: false
    service:
        mailer: at.mailer.twig_swift
    from_email:
        address:  "%mailer_user%"
        sender_name:  "Yziplan"
    registration:
        confirmation:
            enabled: true
            from_email:
                address:  "%mailer_user%"
                sender_name:  "Inscription Yziplan"
        form:
            type: ATUserBundle\Form\InscriptionType
    profile:
        form:
            type: ATUserBundle\Form\UserProfileType

hwi_oauth:
    firewall_names: [main]
    # optional target_path_parameter to provide an explicit return URL
    target_path_parameter: _target_path
    # ne pas utiliser le referer sinon redirection vers le formulaire de login
    use_referer: true
    connect:
        account_connector: at.provider.user
    resource_owners:
        google:
            type:           google
            client_id:      '%oauth.google.id%'
            client_secret:  '%oauth.google.secret%'
            scope:          "email profile"
            options:
                csrf: true
                display: popup
        facebook:
            type:           facebook
            client_id:      '%oauth.facebook.id%'
            client_secret:  '%oauth.facebook.secret%'
            scope:          "email"
            infos_url:      "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email:          email
                profilepicture: picture.data.url
            options:
                csrf: true
                display: popup

    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 10
        # mapping between resource owners (see below) and properties
        properties:
            google: googleId
            facebook: facebookId

fos_comment:
    db_driver: orm
    class:
        model:
            comment: AppBundle\Entity\Comment\Comment
            thread: AppBundle\Entity\Comment\Thread

# Services configurations
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
