# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            user_checker:   at.user_checker
            anonymous:  true
            provider:   main
            form_login:
                login_path:   fos_user_security_login
                check_path:   fos_user_security_check
                success_handler: at.security.ajax_authentication_handler
                failure_handler: at.security.ajax_authentication_handler
                use_referer: true
                default_target_path: home
                target_path_parameter: _target_path
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   fos_user_security_logout
                target: home
            remember_me:
                secret:     '%secret%'
                lifetime:   604800
                path:       /
            oauth:
                login_path:   fos_user_security_login
                use_forward:  true
                failure_path: fos_user_security_login
                default_target_path: home
                success_handler: at.security.ajax_authentication_handler
                failure_handler: at.security.ajax_authentication_handler
                resource_owners:
                    google:   "/login-oauth/check-google"
                    facebook: "/login-oauth/check-facebook"
                oauth_user_provider:
                    service:  at.provider.user