# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    at.service.gentoken.class: AppBundle\Manager\GenerateursToken

services:
# Services & Managers
    at.service.gentoken:
        class: '%at.service.gentoken.class%'

# Autres
    fos_user.doctrine_registry:
        alias: doctrine # Fix Bug with Symphony 3
