services:
# Services & Managers
    at.manager.user_manager:
        class: ATUserBundle\Manager\UserManager
        arguments: ['@security.encoder_factory', '@fos_user.util.username_canonicalizer', '@fos_user.util.email_canonicalizer', '@fos_user.object_manager', '%fos_user.model.user.class%' ]
        calls:
            - [ setTokenGenerateur, ['@at.service.gentoken'] ]
            - [ setEntityManager, ['@doctrine.orm.entity_manager'] ]
            - [ setFosUserProfileFormFactory, ['@fos_user.profile.form.factory'] ]

    at.manager.user_about_manager:
        class: ATUserBundle\Manager\UserAboutManager
        arguments: ['@doctrine.orm.entity_manager','@form.factory']

# Provider
    at.provider.user:
        class: ATUserBundle\Security\ATUserProvider
        arguments: ['@fos_user.user_manager.default',{facebook: facebookId, google: googleId}]
        calls:
            - [ setTokenGenerateur, ['@at.service.gentoken'] ]

# Security services
    at.security.ajax_authentication_handler:
        class: ATUserBundle\Security\AjaxAuthenticationHandler
        arguments: ['@security.http_utils','@router',"@session"]

# EventListeners
    at.event_listener.inscription:
        class: ATUserBundle\EventListener\InscriptionListener
        tags:
            - { name: kernel.event_subscriber }
    at.event_listener.resetting:
        class: ATUserBundle\EventListener\ResettingListener
        tags:
            - { name: kernel.event_subscriber }

# FormTypes
    at.form_type.user_profile:
        class: ATUserBundle\Form\UserProfileType
        tags:
            - { name: form.type, alias: user_user_profile}

    at.form_type.inscription:
        class: ATUserBundle\Form\InscriptionType
        tags:
            - { name: form.type, alias: at_user_registration }

    at.form_type.userabout_biography:
        class: ATUserBundle\Form\UserAboutBiographyType
        tags:
            - { name: form.type, alias: userabout_biography}

    at.form_type.userabout_basicinformation:
        class: ATUserBundle\Form\UserAboutBasicInformationType
        tags:
            - { name: form.type, alias: userabout_basicinformation}

# UserChecker
    at.user_checker:
        class: ATUserBundle\Security\UserChecker

# Voters
