parameters:
    at.manager.user_manager.class: ATUserBundle\Manager\UtilisateurManager
    at.provider.user.class: ATUserBundle\Security\ATUserProvider
    at.event_listener.inscription.class: ATUserBundle\EventListener\InscriptionListener
    at.event_listener.resetting.class: ATUserBundle\EventListener\ResettingListener
    at.form_type.user_profile.class: ATUserBundle\Form\UserProfileType
    at.form_type.inscription.class: ATUserBundle\Form\InscriptionType
    at.checker.user.class: ATUserBundle\Security\UserChecker

services:
# Services & Managers
    at.manager.user_manager:
        class: '%at.manager.user_manager.class%'
        arguments: ['@security.encoder_factory', '@fos_user.util.username_canonicalizer', '@fos_user.util.email_canonicalizer', '@fos_user.object_manager', '%fos_user.model.user.class%' ]
        calls:
            - [ setTokenGenerateur, ['@at.service.gentoken'] ]
            - [ setEntityManager, ['@doctrine.orm.entity_manager'] ]

# Provider
    at.provider.user:
        class: '%at.provider.user.class%'
        arguments: ['@fos_user.user_manager.default',{facebook: facebookId, google: googleId}]
        calls:
            - [ setTokenGenerateur, ['@at.service.gentoken'] ]
# EventListeners
    at.event_listener.inscription:
        class: '%at.event_listener.inscription.class%'
        tags:
            - { name: kernel.event_subscriber }
    at.event_listener.resetting:
        class: '%at.event_listener.resetting.class%'
        tags:
            - { name: kernel.event_subscriber }

# FormTypes
    at.form_type.user_profile:
        class: '%at.form_type.user_profile.class%'
        tags:
            - { name: form.type, alias: user_user_profile}

    at.form_type.inscription:
        class: '%at.form_type.inscription.class%'
        tags:
            - { name: form.type, alias: at_user_registration }

# UserChecker
    at.user_checker:
        class: '%at.checker.user.class%'

# Voters
