<?php

namespace AppBundle\Repository\Payment;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentModuleRepository extends EntityRepository
{
}
