<?php

namespace AppBundle\Repository\Payment;
use Doctrine\ORM\EntityRepository;

/**
 * WalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WalletRepository extends EntityRepository
{
}
