<?php

namespace AppBundle\Repository\payment;

/**
 * WalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WalletRepository extends \Doctrine\ORM\EntityRepository
{
}
