services:
# Services & Managers
  at.service.gentoken:
    class: AppBundle\Manager\GenerateursToken

  at.manager.mangopay:
    class: AppBundle\Manager\MangoPayManager
    arguments: ['%mangopay.client.id%', "%mangopay.client.password%", "%mangopay.temporary.folder%", "%mangopay.base.url%", '@doctrine.orm.entity_manager','@security.authorization_checker']

  at.manager.event:
    class: AppBundle\Manager\EventManager
    arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@form.factory','@at.service.gentoken','@at.manager.module']

  at.manager.module:
    class: AppBundle\Manager\ModuleManager
    arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker','@form.factory','@at.service.gentoken','@templating']

# Voters
  at.voter.event:
    class: AppBundle\Security\EventVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.module:
    class: AppBundle\Security\ModuleVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.eventInvitation:
    class: AppBundle\Security\EventInvitationVoter
    public: false
    tags:
      - { name: security.voter }

# Event Subscribers
  at.event_subscriber.kernel_response.:
    class: AppBundle\EventListener\KernelResponseEventSubscriber
    arguments: ['@translator.default','@session.flash_bag']
    tags:
      - { name: kernel.event_subscriber }