services:
# Services & Managers
  at.service.gentoken:
    class: AppBundle\Manager\GenerateursToken

  at.manager.mangopay:
    class: AppBundle\Manager\MangoPayManager
    arguments: ['%mangopay.client.id%', "%mangopay.client.password%", "%mangopay.temporary.folder%", "%mangopay.base.url%", '@doctrine.orm.entity_manager','@security.authorization_checker']

  at.manager.event:
    class: AppBundle\Manager\EventManager
    arguments: ['@doctrine.orm.entity_manager','@security.token_storage','@security.authorization_checker','@form.factory','@at.service.gentoken','@at.manager.module','@at.manager.event_invitation','@at.manager.module_invitation']

  at.manager.module:
    class: AppBundle\Manager\ModuleManager
    arguments: ['@doctrine.orm.entity_manager','@security.token_storage','@security.authorization_checker','@form.factory','@at.service.gentoken','@templating', '@at.manager.module_invitation']

  at.manager.event_invitation:
    class: AppBundle\Manager\EventInvitationManager
    arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker', '@form.factory', '@at.service.gentoken', '@session', '@at.manager.user_manager','@at.manager.module_invitation']

  at.manager.module_invitation:
      class: AppBundle\Manager\ModuleInvitationManager
      arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker', '@at.service.gentoken']

  at.manager.pollproposal:
      class: AppBundle\Manager\PollProposalManager
      arguments: ['@form.factory']

  at.manager.pollproposal_response:
      class: AppBundle\Manager\PollProposalResponseManager
      arguments: ['@doctrine.orm.entity_manager']

  at.service.mailer:
    class: AppBundle\Mailer\ATTwigSwiftMailer
    arguments: ['@mailer','@router','@templating','@translator.default']

# Voters
  at.voter.event:
    class: AppBundle\Security\EventVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.module:
    class: AppBundle\Security\ModuleVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.event_invitation:
    class: AppBundle\Security\EventInvitationVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.module_invitation:
    class: AppBundle\Security\ModuleInvitationVoter
    public: false
    tags:
      - { name: security.voter }

# FormTypes
  at.form_type.invitation:
    class: AppBundle\Form\InvitationsFormType
    arguments: ['@security.authorization_checker', '@security.token_storage', '@validator']
    tags:
    - { name: form.type }

# Event Subscribers
  at.event_subscriber.kernel_events.:
    class: AppBundle\EventListener\KernelEventsSubscriber
    arguments: ['@translator.default','@session.flash_bag','@router']
    tags:
      - { name: kernel.event_subscriber }