services:
# Services & Managers
  at.service.gentoken:
    class: AppBundle\Manager\GenerateursToken

  at.updater.canonical_fields:
    class: AppBundle\Utils\User\CanonicalFieldsUpdater
    parent: fos_user.util.canonical_fields_updater

  at.uploader.avatar:
    class: AppBundle\Utils\File\FileUploader
    arguments: ['%avatar_directory%', 'avatar']

  at.uploader.event_picture:
    class: AppBundle\Utils\File\FileUploader
    arguments: ['%event_picture_directory%', 'event_picture']

  at.manager.mangopay:
    class: AppBundle\Manager\MangoPayManager
    arguments: ['%mangopay.client.id%', "%mangopay.client.password%", "%mangopay.temporary.folder%", "%mangopay.base.url%", '@doctrine.orm.entity_manager','@security.authorization_checker']

  at.manager.event:
    class: AppBundle\Manager\EventManager
    arguments: [ '@doctrine.orm.entity_manager','@security.token_storage','@security.authorization_checker','@form.factory','@at.service.gentoken','@at.manager.module','@at.manager.pollproposal','@at.manager.event_invitation','@at.manager.module_invitation']

  at.manager.module:
    class: AppBundle\Manager\ModuleManager
    arguments: ['@doctrine.orm.entity_manager','@security.token_storage','@security.authorization_checker','@form.factory','@at.service.gentoken','@templating', '@at.manager.module_invitation','@at.manager.pollproposal']

  at.manager.event_invitation:
    class: AppBundle\Manager\EventInvitationManager
    arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker', '@form.factory', '@at.service.gentoken', '@session', '@at.manager.application_user','@at.manager.module_invitation']

  at.manager.module_invitation:
      class: AppBundle\Manager\ModuleInvitationManager
      arguments: ['@doctrine.orm.entity_manager','@security.authorization_checker', '@at.service.gentoken']

  at.manager.pollproposal:
      class: AppBundle\Manager\PollProposalManager
      arguments: ['@doctrine.orm.entity_manager','@form.factory','@templating']
      lazy:  true

  at.manager.pollproposal_response:
      class: AppBundle\Manager\PollProposalResponseManager
      arguments: ['@doctrine.orm.entity_manager']

  at.manager.application_user:
    class: AppBundle\Manager\ApplicationUserManager
    arguments: ['@doctrine.orm.entity_manager','@fos_user.util.email_canonicalizer','@translator.default','@fos_user.util.token_generator']

  at.manager.app_user_information:
      class: AppBundle\Manager\AppUserInformationManager
      arguments: ['@doctrine.orm.entity_manager','@form.factory','@at.uploader.avatar']

  at.manager.contact:
      class: AppBundle\Manager\ContactManager
      arguments: ['@doctrine.orm.entity_manager','@at.manager.user']

# Voters
  at.voter.event:
    class: AppBundle\Security\EventVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.module:
    class: AppBundle\Security\ModuleVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.event_invitation:
    class: AppBundle\Security\EventInvitationVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.module_invitation:
    class: AppBundle\Security\ModuleInvitationVoter
    public: false
    tags:
      - { name: security.voter }

  at.voter.contact:
    class: AppBundle\Security\ContactVoter
    public: false
    tags:
      - { name: security.voter }

# FormTypes
  at.form_type.invitation:
    class: AppBundle\Form\Event\InvitationsFormType
    arguments: ['@security.authorization_checker', '@security.token_storage', '@validator']
    tags:
    - { name: form.type }

# Event Subscribers
  at.event_subscriber.kernel_events.:
    class: AppBundle\EventListener\KernelEventsSubscriber
    arguments: ['@translator.default','@session.flash_bag','@router']
    tags:
      - { name: kernel.event_subscriber }

  at.event_listener.appuseremail_confirmation:
    class: AppBundle\EventListener\AppUserEmailConfirmationSubscriber
    arguments: ['@at.mailer.twig_swift','@fos_user.util.token_generator','@router']
    tags:
      - { name: kernel.event_subscriber }

  at.event_listener.avatar_upload:
    class: AppBundle\EventListener\User\AvatarUploadListener
    arguments: ['@at.uploader.avatar']
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }

  at.event_listener.event_picture_upload:
    class: AppBundle\EventListener\Event\EventUploadListener
    arguments: ['@at.uploader.event_picture']
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }

# Validator Constraints
  at.validator.email_not_belong_to_useraccount:
    class: AppBundle\Validator\Constraints\EmailNotBelongToAccountUserValidator
    arguments: ['@at.manager.application_user']
    tags:
      - { name: validator.constraint_validator }

# Twig Extenstions
  at.twig_extension.country:
        class: AppBundle\Twig\CountryExtension
        public: false
        tags:
            - { name: twig.extension }
