<?php

namespace AppBundle\Repository\Notifications;

/**
 * EventInvitationNotificationPreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventInvitationPreferencesRepository extends \Doctrine\ORM\EntityRepository
{
}
