<?php

namespace AppBundle\Repository\Event;

use Doctrine\ORM\EntityRepository;

/**
 * EventOpeningHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventOpeningHoursRepository extends EntityRepository
{
}
