<?php

namespace AppBundle\Repository\Event;

use Doctrine\ORM\EntityRepository;

/**
 * EventCoordinatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCoordinatesRepository extends EntityRepository
{
}
