<?php

namespace AppBundle\Repository\Event;

use Doctrine\ORM\EntityRepository;

/**
 * EventInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventInvitationRepository extends EntityRepository
{
}
