<?php

namespace AppBundle\Repository\Event;

use Doctrine\ORM\EntityRepository;

/**
 * EventInvitationNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventInvitationNotificationRepository extends EntityRepository
{
}