<?php

namespace AppBundle\Repository\Event;
use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{

    public function findOrderedByEventToken($eventToken)
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT m, -m.orderIndex AS HIDDEN inversedOrderIndex FROM AppBundle:Module m WHERE m.event = 
                          (SELECT e FROM AppBundle:Event e WHERE e.token = :eventToken)
                          ORDER BY inversedOrderIndex DESC"
        );
        $query->execute(array(
            'eventToken' => $eventToken
        ));
        return $query->getResult();
    }

}
