<?php

namespace AppBundle\Repository\Event;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleInvitationRepository extends EntityRepository
{
}
