<?php

namespace AppBundle\Repository\User;
use Doctrine\ORM\EntityRepository;

/**
 * ApplicationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationUserRepository extends EntityRepository
{
}
