<?php

namespace AppBundle\Repository\User;

/**
 * AppUserInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppUserInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
