<?php

namespace AppBundle\Repository\User;

use Doctrine\ORM\EntityRepository;

/**
 * ContactEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactEmailRepository extends EntityRepository
{
}
